### ISSUE TITLE
wp_editor in Metabox or Options will re-format content upon save

### ISSUE THREAD

**Issue by dameer** [vafour/vafpress-framework#26]
For some reason, when used with Metabox or Options, "wp_editor" doesn't keep content formatted in tinyMCE upon save, it'll rather tend to "compress" it and thus create unreadable chunk of text. That's really annoying, especially when the content is mixed up with shortcode placeholders or even worse - photos.

Is there a way to use (or include) "wp_editor" identical to the one used with Post or Page editor where users can switch between Visual and Text (html) mode?

I know that there is "HTML view" available whenever "wp_editor" is included to   Metabox, however, HTML looks identical to tinyMCE - a big pile of letters, HTML tags and shortcode placeholders. It's totally useless.

**Comment by dameer** [comment]
I've been checking out source code a bit... Please have a look at "vafpress/classes/control/wpeditor.php", line #69 ...
Shouldn't it be

```
$_value = str_replace(array("\r\n", "\r"), "<br />", $_value);
```

...instead of default

```
$_value = str_replace(array("\r\n", "\r"), "\n", $_value);
```

For some reason tinyMCE doesn't make line breaks.

**Comment by ayublin** [comment]
Hi Dameer,

we're not experiencing the issue you mentioned, are you running the latest version of Vafpress Framework? Do you get any PHP error/notice or browser's JavaScript console?

The issue you mentioned did existed but not upon saving, it was happening upon metabox sorting, and it's been fixed long ago.

It's hard to mimic the main WP TinyMCE post editor, since the HTML tab isn't a native feature of tinyMCE but a custom tinyMCE plugin developed by WordPress.

And as for the code changes you shown, we don't think it has something to do with that line of code.

Thanks!

**Comment by dameer** [comment]
Maybe you got me wrong because I wasn't clear enough. I'm sure you can reproduce the problem, Page Builder would be a perfect example (Vafpress Framework Documentation > Usage Sample >> Page Builder). Try to copy-paste the following, sample shortcodes+text mix:

```
[page_blox_container textalign="text-left" text_shadow="text-shadow-light" primeblock="true"]

[row text_shadow="none"]

[column col="4"] 

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada nunc a lectus feugiat volutpat a sed massa. Mauris cursus urna eget cursus dignissim.

[/column]

[column col="8"]

Pellentesque rhoncus diam ut massa iaculis consequat. Nulla sit amet sem ut risus congue adipiscing sit amet ut enim. Cras ac malesuada libero. Nullam fermentum sollicitudin erat. Pellentesque habitant morbi tristique senectus. 

[gap height="30"]

[button style="btn-danger" size="default" label="Action button" icon="icon-thumbs-up" link="http://google.com" link_opens="_blank"]

[/column]

[/row]

[/page_blox_container]
```

It doesn't really matter whether the above shortcodes exist in your WP theme, it's only for the illustration purpose! Once you paste it into WP editor used by Metabox and save your test Post or Page you'll find it being compressed into one line, without a single line break - even though line breaks were there before saving.
It's due to the fact that this line

```
$_value = str_replace(array("\r\n", "\r"), "\n", $_value);
```

does not do anything. TinyMCE relies on HTML.

And yes, I do have the latest Vafpress. No HTML, javascript or server errors and described problem persist in each and every Browser which means it is tinyMCE related.

**Comment by ayublin** [comment]
Hi Dameer,

We tried the case with the text you provided by still got no issue. Can you please try disabling all of your plugins?

**Comment by dameer** [comment]
I do not have any plugins installed whenever the site is in development stage. But thanks for taking look anyway. I just can't believe that our platforms are so different. If you don't see that the line breaks are getting ignored for shortcode placeholders then I can only seek for a solution by myself.
Cheers!

**Comment by ayublin** [comment]
Hi Dameer,

You're welcome! but I would love to get this issue resolved, let's dig a bit deeper. Can you give me your environment informations? Like OS, PHP version, WP version and etc.

Thanks!

**Comment by dameer** [comment]
MacOS X 10.8.5
(XAMPP) PHP 5.3.1
WordPress 3.6.1
I'm sure that none of these affects tinyMCE misbehavior :)

Would it make more sense if I provide a screen shot of how things look in editor? Here it is:

![mess](https://f.cloud.github.com/assets/1826261/1379548/44e4b57e-3af1-11e3-8375-4a70d04e55bf.png)

So once again ...
No matter how many line breaks are used to visually separate shortcode placeholders from the content, upon Post/Page save everything gets compressed.

And this is how it looks like in "regular" Post or Page editor, everything stays in place, line breaks are preserved

![tidy](https://f.cloud.github.com/assets/1826261/1379565/f6c60054-3af1-11e3-804a-f7c516fa1a92.png)

**Comment by dameer** [comment]
OK, I think I'm finally on the right track. After doing numerous tests which ended up either as non-reliable or non-convenient, the answer was right under my nose, as simple and elegant as WP actually is.

So, take a look back at the file "vafpress/classes/control/field/wpeditor.php", line #69...

```
$_value = str_replace(array("\r\n", "\r"), "\n", $_value);
```

Text formatting must be preserved not "normalized", that's what WordPress do to filter the_content(). I guess Metabox/Options wp_editor should do the same. And instead of "normalizing" new lines, just preserve formatting

```
$_value = wpautop( $_value );
```

Hopefully it helps!

**Comment by ayublin** [comment]
Hi dameer,

I see, we never tested the framework on Mac OS devices. I am not sure what is the line break character for your OS. Can you please try removing the line:

`$_value = str_replace(array("\r\n", "\r"), "\n", $_value);`

And see what's the result?

I really thank you for helping us finding a solution for this! You're right `wpautop` is being used in `the_content`, but it's used exactly before WP render the data, while the post data in database should stays raw un-wpautop-ed.

**Comment by ayublin** [comment]
I just pushed some changes, please use the latest commits and see if the issue fixed, looking forward to hear from you! :)

**Comment by dameer** [comment]
`array("\r\n", "\r")` stands for both Windows and MacOS platform :)
...and YES, of course I have tried to disable the line #69, it has no impact on text formatting. You have remove it in your latest commit of "wp-editor.php" which is just fine except the fact that the problem still persist.
`wpautop` is used to format the text of `the_content` and in your case it is used to format the text for tinyMCE, it just spits it out properly formatted, that's all.
If you give it a shot you'll realize what I am talking about.

**Comment by ayublin** [comment]
Hi Dameer,

Yes I have tried using `wpautop` when I was developing the control, it does preserve the line break, but there is a problem. You can try creating a post with the main content having some line breaks, and please examine the post content in the database, then you should see the content saved with line break, not with `<p>`, if we use `$_value = wpautop( $_value );` the saved content will be wrapped by html `p` tags, and that's not the expected behavior.

Then to solve the line break issue, I mimic the way WP main post content editor works. It's using `the_editor_content` filter which is doing `wp_richedit_pre` function to the content of the textarea that will be turned to TinyMCE editor.

If you examine what `wp_richedit_pre` function does, is actually including `$output = wpautop($output);`, so the `wpautop` is done upon displaying the TinyMCE editor, and the data saved still having line breaks instead of being `wpautop`-ed.

Can you test and see what's the content in your database with and without `wpautop`?

I have tested this in Windows and Linux machines, both in options page or metabox, but they're working well, I really got to test this in Mac machine :|

Thanks!

**Comment by dameer** [comment]
There's no need to mimic anything, it's as simple as it can be: whenever `wp_editor()` is used with TEXTAREA element, `wpautop` must be applied on content getting displayed in tinyMCE.
Next, no need to worry how `wp_editor` content is saved to database; it's saved as What You See Is What You Get, regardless the platform.
Here's an evidence.

![no_wpautop](https://f.cloud.github.com/assets/1826261/1415105/d77dd76e-3edc-11e3-95aa-6a041a5bb376.png)

![wpautop](https://f.cloud.github.com/assets/1826261/1415106/dc0af3fc-3edc-11e3-983a-6390d727c58d.png)

![regular_post_wpautop](https://f.cloud.github.com/assets/1826261/1415107/df4d1ad6-3edc-11e3-9c2e-3c3c378eefb1.png)

**Comment by ayublin** [comment]
> There's no need to mimic anything, it's as simple as it can be: whenever wp_editor() is used with TEXTAREA > element, wpautop must be applied on content getting displayed in tinyMCE.

That's what exactly we have done, and we did it by examining (mimicking) WP main post editor:
https://github.com/vafour/vafpress-framework/blob/master/views/control/wpeditor.php#L3-L16

`wpautop` has been applied upon displaying the content via `the_editor_content` filter.

**Comment by dameer** [comment]
Don't get me wrong Ayublin, I don't want to argue, just wanna help but your method does not score expected result for me. A couple of minutes ago I have re-tested all on HP Envy running Windows 7 and there's actually no difference between MacOS and Win - the problem with misformatting is still there without `wpautop`. I'm not asking you to commit the file change, my client want's to keep the content tidy so I have no other option but to 
`$_value = wpautop( $_value );`
Hopefully you don't mind. Thanks for your efforts!

**Comment by ayublin** [comment]
Of course not dameer :) I really appreciate your helps! And I can understand your situation, no clients would want their content messed like that. It's really weird that the current method isn't working at your end since the `wpautop` also applied, if you have the time that would be cool if you can test to see how the `$value` looking before and after those code https://github.com/vafour/vafpress-framework/blob/master/views/control/wpeditor.php#L3-L10.

Thanks again!

**Comment by dameer** [comment]
I already have tested `wp_editor` with the latest commits :) Those database shots were made with the latest Vafpress as well.
